shipsear_class_12 = ['Dredger', 'Passengers', 'Tugboat', 'Ocean liner', 'Motorboat', 'RORO', 'Trawler', 'Pilot ship', 'Sailboat', 'Mussel boat', 'Fishboat', 'Natural ambient noise']
shipsear_class_5 = ['Fishboat','Motorboat','Passengers ship', 'RORO', 'Noise']
deepship_class = ['Cargo', 'Passengership', 'Tanker', 'Tug']
ocean_class = ['Fishing', 'Towing', 'Dredging', 'Diving ship', 'Military ship', 'Sailing', 'Pleasure Craft', 'Pilot Vessel', 'Search and Rescue vessel', 'Tug', 'Port Tender', 'Anti-pollution equipment', 'Law Enforcement', 'Spare', 'Medical Transport', 'Passenger', 'Cargo', 'Tanker']
cdclass = ['Fishing', 'Motorboat', 'Port Tender', 'Spare', 'Trawler', 'Diving ship', 'Dredging', 'Towing', 'Search and Rescue vessel', 'Cargo', 'Pilot Vessel', 'Tanker', 'Pleasure Craft', 'Passenger', 'RORO', 'Sailboat', 'Military ship', 'Tug', 'Ocean liner', 'Mussel boat', 'Law Enforcement', 'Anti-pollution equipment', 'Medical Transport', 'Natural ambient noise', 'Sailing']
cddeepship = ['Tug','Tanker','Cargo','Passenger']
cdshipsear = ['Dredging','Ocean liner','Fishing','Passenger','Trawler','Tug','Pilot Vessel','Motorboat','RORO','Mussel boat','Sailboat','Natural ambient noise']